Attempted pickling UKF - FAIL
Can't seem to pickle due to abstract super class:

TypeError: Can't instantiate abstract class StateEstimator with abstract methods estimate, x